#!/usr/bin/python3
# encoding=UTF-8

# Copyright © 2012-2025 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

'''
Convert some 822 files hosted on ftp-master to the Atom syndication format.

Supported files:
* https://ftp-master.debian.org/new.822
* https://ftp-master.debian.org/deferred/status
'''

import abc
import argparse
import datetime
import email.utils
import re
import sys
import textwrap

import lxml.etree as etree

import apt_pkg

0_0  # Python >= 3.6 is required

ns_atom = 'http://www.w3.org/2005/Atom'
ns_xhtml = 'http://www.w3.org/1999/xhtml'

def rfc3339(date):
    date = date.replace(microsecond=0)
    return str(date).replace(' ', 'T')

def elem(parent, name, tail='\n', nsmap=None, **attrib):
    if parent.text is None:
        parent.text = '\n'
    result = etree.SubElement(parent, name, attrib=attrib, nsmap=nsmap)
    result.tail = tail
    return result

def parse_addr(addr):
    try:
        name, email = addr.split('<', 1)
    except ValueError:
        name = None
        email = addr
    else:
        name = name.strip()
        email = email.rstrip('>')
    return name, email

def fix_email(email):
    # work-around for bug #662024
    return re.sub('(.*@.*)(@debian[.]org)$', r'\1', email)

def read_tag_file(file):
    return apt_pkg.TagFile(file)

class converter(abc.ABC):

    @abc.abstractmethod
    def get_title(self):
        pass

    @abc.abstractmethod
    def get_self_uri(self):
        pass

    def get_extra_uris(self):
        return ()

    @abc.abstractmethod
    def get_entry_uri(self, para):
        pass

    @abc.abstractmethod
    def get_entry_timestamp(self, para):
        pass

    @abc.abstractmethod
    def get_changes_base_uri(self):
        pass

    def __call__(self):
        feed = etree.Element('feed', nsmap={None: ns_atom})
        e_title = elem(feed, 'title')
        e_title.text = self.get_title()
        e_id = elem(feed, 'id')
        e_id.text = 'https://ftp-master.debian.org/new.atom'
        elem(feed, 'link', rel='self', type='application/atom+xml', href=self.get_self_uri())
        for media_type, alternate_uri in self.get_alternate_uris():
            elem(feed, 'link', rel='alternate', type=media_type, href=alternate_uri)
        e_updated = elem(feed, 'updated')
        e_updated.text = rfc3339(datetime.datetime.now(datetime.timezone.utc))
        e_updated.tail += '\n'
        for para in read_tag_file(sys.stdin):
            uri = self.get_entry_uri(para)
            entry = elem(feed, 'entry')
            if uri is not None:
                elem(entry, 'link', href=uri)
            e_title = elem(entry, 'title')
            e_title.text = changes = para['Changes-File']
            timestamp = self.get_entry_timestamp(para)
            e_ident = elem(entry, 'id')
            base_uri = self.get_changes_base_uri()
            e_ident.text = f'{base_uri}{changes}#{rfc3339(timestamp)}'
            e_updated = elem(entry, 'updated')
            e_updated.text = rfc3339(timestamp)
            author_name, author_email = parse_addr(para['Changed-By'])
            if author_name is None:
                author_name = author_email
            e_author = elem(entry, 'author')
            e_author_name = elem(e_author, 'name')
            e_author_name.text = author_name
            e_author_email = elem(e_author, 'email')
            e_author_email.text = author_email
            try:
                sponsor_email = para['Sponsored-By']
            except LookupError:
                pass
            else:
                sponsor_email = fix_email(sponsor_email)
                e_sponsor = elem(entry, 'contributor')
                e_sponsor_name = elem(e_sponsor, 'name')
                e_sponsor_name.text = sponsor_email  # FIXME!
                e_sponsor_email = elem(e_sponsor, 'email')
                e_sponsor_email.text = sponsor_email
            e_content = elem(entry, 'content', type='xhtml')
            e_div = elem(e_content, 'div', nsmap={None: ns_xhtml})
            e_pre = elem(e_div, 'pre')
            e_pre.text = str(para)
            entry.tail += '\n'
        feed.tail = '\n'
        etree.ElementTree(feed).write(sys.stdout.buffer)

class convert_new(converter):

    def get_title(self):
        return 'Debian NEW and BYHAND Packages'

    def get_self_uri(self):
        return 'https://ftp-master.debian.org/new.atom'

    def get_alternate_uris(self):
        yield 'text/html', 'https://ftp-master.debian.org/new.html'
        yield 'text/plain', 'https://ftp-master.debian.org/new.822'

    def _get_entry_epochless_version(self, para):
        version = para['Version'].split()[0]
        if ':' in version:
            _, epochless_version = version.split(':', 1)
            return epochless_version
        else:
            return version

    def get_entry_uri(self, para):
        source = para['Source']
        version = self._get_entry_epochless_version(para)
        return f'https://ftp-master.debian.org/new/{source}_{version}.html'

    def get_entry_timestamp(self, para):
        return datetime.datetime.fromtimestamp(
            int(para['Last-Modified']),
            datetime.timezone.utc
        )

    def get_changes_base_uri(self):
        return 'https://ftp-master.debian.org/new/'

class convert_deferred(converter):

    def get_title(self):
        return 'Deferred upload to Debian'

    def get_self_uri(self):
        return 'https://ftp-master.debian.org/deferred.atom'

    def get_alternate_uris(self):
        yield 'text/html', 'https://ftp-master.debian.org/deferred.html'
        yield 'text/plain', 'https://ftp-master.debian.org/deferred/status'

    def get_entry_timestamp(self, para):
        timetuple = email.utils.parsedate_tz(para['Date'])
        timestamp = datetime.datetime(*timetuple[:7])
        timestamp -= datetime.timedelta(seconds=timetuple[9])
        return timestamp

    def get_entry_uri(self, para):
        base_uri = self.get_changes_base_uri()
        changes = para['Changes-File']
        return f'{base_uri}{changes}'

    def get_changes_base_uri(self):
        return 'https://ftp-master.debian.org/deferred/'

def main():
    ap = argparse.ArgumentParser(formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--type', choices=('new', 'deferred'), required=True,
        metavar='TYPE', help='status file type to parse: new[1] or deferred[2]'
    )
    ap.epilog = textwrap.dedent('''
        [1] https://ftp-master.debian.org/new.822
        [2] https://ftp-master.debian.org/deferred/status
    ''')
    options = ap.parse_args()
    converter = globals()[f'convert_{options.type}']()
    return converter()

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
