#!/usr/bin/python3

# Copyright © 2013 Jakub Wilk <jwilk@debian.org>

# Redistribution and use in source and compiled forms, with or without
# modification, are permitted under any circumstances. No warranty.

import argparse
import hashlib
import os
import subprocess as ipc
import sys

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--method', choices=('upgrade', 'dist-upgrade'), default='dist-upgrade')
    options = ap.parse_args()
    cmdline = [
        'apt-get',
        options.method,
        '-qqy',
        '--print-uris',
    ]
    raw_expected = ipc.check_output(cmdline)
    raw_expected = raw_expected.splitlines()
    expected = {}
    print('#!/bin/sh')
    for line in raw_expected:
        url, name, _, _ = line.split()
        name = name.decode('ASCII')
        url = url.decode('ASCII')
        print('wget', url, '-O', name)

if __name__ == '__main__':
    main()

# vim:ts=4 sw=4 et
