#!/usr/bin/python3

# Copyright © 2013-2014 Jakub Wilk <jwilk@jwilk.net>

# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED “AS IS” AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

import argparse
import subprocess as ipc

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--method', choices=('upgrade', 'dist-upgrade'), default='dist-upgrade')
    options = ap.parse_args()
    cmdline = [
        'apt-get',
        options.method,
        '-qqy',
        '--print-uris',
    ]
    raw_expected = ipc.check_output(cmdline)
    raw_expected = raw_expected.splitlines()
    print('#!/bin/sh')
    simple_urls = []
    for line in raw_expected:
        url, name, _, _ = line.split()
        name = name.decode('ASCII')
        url = url.decode('ASCII')
        if url.endswith("/{name}'".format(name=name)):
            simple_urls += [url]
        else:
            print('wget', url, '-O', name)
    if simple_urls:
        print('wget', *simple_urls)

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
