#!/usr/bin/python3

# Copyright © 2013-2017 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import argparse
import subprocess as ipc
import tempfile

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('cmd', metavar='APT-CMD', default='dist-upgrade', nargs='?')
    ap.add_argument('args', metavar='APT-ARGS', nargs=argparse.REMAINDER)
    options = ap.parse_args()
    cmdline = [
        'apt-get',
        options.cmd,
        '-qqy',
        '--print-uris',
    ] + options.args
    with tempfile.TemporaryDirectory(prefix='apt-wget.') as tmpdir:
        raw_expected = ipc.check_output(cmdline, cwd=tmpdir)
    raw_expected = raw_expected.splitlines()
    print('#!/bin/sh')
    simple_urls = []
    for line in raw_expected:
        url, name, *_ = line.split()
        name = name.decode('ASCII')
        url = url.decode('ASCII')
        if url.endswith("/{name}'".format(name=name)):
            simple_urls += [url]
        else:
            print('wget', url, '-O', name)
    if simple_urls:
        print('wget', *simple_urls)

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
