#!/bin/sh

# Copyright © 2010, 2011 Jakub Wilk <jwilk@debian.org>

# Redistribution and use in source and compiled forms, with or without
# modification, are permitted under any circumstances. No warranty.

regex=$(sed -e 's/\([.+]\)/\\\1/g' | tr '\n' '|')
regex="(^| )(${regex%|})(,|$)"
grep-aptavail -F Package -e "$regex" -s Package,Source \
| tbl-dctrl -c Source -c Package -d ' ' -H \
| sed -e 's/^ //; s/ .*//' \
| sort -u
