#!/bin/sh

# Copyright © 2010-2018 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

regex=$(sed -e 's/\([.+]\)/\\\1/g' | tr '\n' '|')
regex="(^| )(${regex%'|'})(,|$)"
grep-aptavail -F Package -e "$regex" -n -s Source:Package \
| cut -d ' ' -f 1 \
| sort -u
