#!/bin/sh

# Copyright © 2010-2022 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

regexp=$(sed -e 's/\([.+]\)/\\\1/g' | tr '\n' '|')
regexp="(^| )(${regexp%'|'})(,|$)"
grep-aptavail -F Package -e "$regexp" -n -s Source:Package \
| cut -d ' ' -f 1 \
| sort -u
