#!/usr/bin/python3

# Copyright © 2022 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import argparse
import logging
import re

import debianbts

0_0  # Python >= 3.6 is required

check_subject = re.compile(r'(O|RFA|RFH|ITA|ITP|RFP): [a-z0-9][a-z0-9+.-]+ -- \S.*(?<=\S)').fullmatch

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--bad-subject', action='store_true')
    options = ap.parse_args()
    logging.getLogger('pysimplesoap.simplexml').setLevel(logging.CRITICAL)
    bugs = debianbts.get_bugs(package='wnpp')
    bugs.sort(reverse=True)
    batch_size = 100
    for i in range(0, len(bugs), batch_size):
        chunk = bugs[i:(i + batch_size)]
        chunk = debianbts.get_status(chunk)
        for bug in chunk:
            assert not bug.archived
            if options.bad_subject and check_subject(bug.subject):
                continue
            if any(n < bug.bug_num for n in bug.mergedwith):
                continue
            print(f'#{bug.bug_num} {bug.subject}')

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
