#!/usr/bin/python3
# encoding=UTF-8

# Copyright © 2015 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import argparse

import debian.debian_support as deb

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('v1', metavar='VER1')
    ap.add_argument('v2', metavar='VER2')
    opt = ap.parse_args()
    op = ['<<', '=', '>>'][1 + deb.version_compare(opt.v1, opt.v2)]
    print(opt.v1, op, opt.v2)

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
