#!/usr/bin/python3

# Copyright © 2015 Jakub Wilk <jwilk@debian.org>

# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED “AS IS” AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

import argparse

import debian.debian_support as deb

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('v1', metavar='VER1')
    ap.add_argument('v2', metavar='VER2')
    opt = ap.parse_args()
    op = ['<<', '=', '>>'][1 + deb.version_compare(opt.v1, opt.v2)]
    print(opt.v1, op, opt.v2)

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
