#!/usr/bin/python3
# encoding=UTF-8

# Copyright © 2015-2025 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import sys

import debian.deb822 as deb

0_0  # Python >= 3.6 is required

def main():
    for pkg in deb.Packages.iter_paragraphs(sys.stdin):
        size = 0
        for line in pkg['Files'].splitlines():
            if not line:
                continue
            size += int(line.split()[1])
        pkgname = pkg['Package']
        version = pkg['Version']
        print(f'{size}\t{pkgname}\t{version}')

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
