#!/usr/bin/python3

# Copyright © 2015 Jakub Wilk <jwilk@debian.org>

# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED “AS IS” AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

import sys

import debian.deb822 as deb

def main():
    for pkg in deb.Packages.iter_paragraphs(sys.stdin):
        size = 0
        for line in pkg['Files'].splitlines():
            if not line:
                continue
            size += int(line.split()[1])
        print('{size}\t{pkg}\t{ver}'.format(size=size, pkg=pkg['Package'], ver=pkg['Version']))

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
