#!/usr/bin/python3
# encoding=UTF-8

# Copyright © 2012-2025 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

'''
This program edits (in-place) a (DEBIAN/)control file:
- demoting some Depends to Recommends;
- changing (= $version) to (= $another_version).

It's useful as a hook for deb-reversion.
'''

import argparse
import re
import sys

import apt_pkg

0_0  # Python >= 3.6 is required

def do_edit(options):
    [para] = apt_pkg.TagFile(options.ctrlfile)
    try:
        depends = para['Depends']
    except LookupError:
        return
    depends = [d.strip() for d in depends.split(',')]
    try:
        recommends = [para['Recommends']]
    except LookupError:
        recommends = []
    new_depends = []
    r_alternative = str.join('|', (re.escape(x) for x in options.demote))
    demote_regex = re.compile(f'^({r_alternative})( .*)?$')
    for depends in depends:
        if demote_regex.match(depends):
            recommends += [depends]
        else:
            new_depends += [depends]
    new_depends = ', '.join(new_depends)
    if options.fix_version is not None:
        para_version = para['Version']
        new_depends = new_depends.replace(
            f'(= {para_version})',
            f'(= {options.fix_version})',
        )
    recommends = ', '.join(recommends)
    options.ctrlfile.seek(0)
    options.ctrlfile.truncate()
    sys.stdout = options.ctrlfile
    for line in str(para).splitlines():
        if line.startswith('Depends:'):
            print(f'Depends: {new_depends}')
            if recommends:
                print(f'Recommends: {recommends}')
        elif line.startswith('Recommends:'):
            pass
        else:
            print(line)

def main():
    apt_pkg.init()
    parser = argparse.ArgumentParser()
    parser.add_argument('--demote', metavar='LIBRARY', action='append', default=[])
    parser.add_argument('--fix-version', metavar='VERSION')
    parser.add_argument('ctrlfile', metavar='CONTROL-FILE', type=argparse.FileType('r+'))
    options = parser.parse_args()
    do_edit(options)

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
