#!/usr/bin/python3
# encoding=UTF-8

# Copyright © 2011-2015 Jakub Wilk <jwilk@debian.org>

# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED “AS IS” AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

import argparse
import sys

import debian.deb822 as deb822

fields = [
    'Depends', 'Recommends', 'Suggests', 'Enhances',
    'Conflicts', 'Breaks', 'Replaces',
]

alt_all = object()
alt_every = object()
alt_first = object()

def parse(file, options):
    for pkg in deb822.Packages.iter_paragraphs(file):
        pkg_name = pkg['Package']
        for field in fields:
            try:
                relations = pkg[field]
            except LookupError:
                continue
            relations = deb822.PkgRelation.parse_relations(relations)
            for relation in relations:
                if options.ignore_versions:
                    for subrelation in relation:
                        subrelation['version'] = None
                if options.alternatives is alt_all:
                    value = deb822.PkgRelation.str([relation])
                    print('{package}\t{field}\t{value}'.format(package=pkg_name, field=field, value=value))
                else:
                    for subrelation in relation:
                        subvalue = deb822.PkgRelation.str([[subrelation]])
                        print('{package}\t{field}\t{value}'.format(package=pkg_name, field=field, value=subvalue))
                        if options.alternatives is alt_first:
                            break

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--ignore-versions', action='store_true')
    parser.set_defaults(alternatives=alt_all)
    parser.add_argument('--every-alternative', action='store_const', const=alt_every, dest='alternatives')
    parser.add_argument('--first-alternative', action='store_const', const=alt_first, dest='alternatives')
    options = parser.parse_args()
    parse(sys.stdin, options)

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
