#!/usr/bin/python3

# Copyright © 2015 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import sys

import debian.deb822 as deb

def main():
    for pkg in deb.Packages.iter_paragraphs(sys.stdin):
        size = 0
        for line in pkg['Files'].splitlines():
            if not line:
                continue
            size += int(line.split()[1])
        print('{size}\t{pkg}\t{ver}'.format(size=size, pkg=pkg['Package'], ver=pkg['Version']))

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
