#!/usr/bin/perl

# Copyright © 2014 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

use strict;
use warnings;

use v5.10;

if (scalar @ARGV < 1) {
    say STDERR "usage: $0 <deb>...";
    exit 1;
}

my @PATH = qw(/bin /usr/bin /sbin /usr/sbin /usr/games);
my $PATH = join('|', @PATH);
$PATH = qr($PATH);

my %files = ();
for my $deb (@ARGV) {
    open my $fh, '-|', 'dpkg', '-c', $deb or die;
    while (<$fh>) {
        m{[.](/.*)$} or die "$0: cannot parse $_";
        my $file = $1;
        next if $file eq '/';
        if ($file =~ m{^$PATH/(.+)}) {
            my $rest = $1;
            for my $dir (@PATH) {
                $files{"$dir/$rest"} = 1;
            }
        } else {
            $file =~ s{/$}{};
            $files{$file} = 1;
        }
    }
    close $fh or die;
}
my @files = sort keys %files;

open my $fh, '|-', 'apt-file', 'search', '-F', '-f', '-' or die;
for my $file (@files) {
    say {$fh} $file;
}
close $fh or die;

# vim:ts=4 sts=4 sw=4 et
