#!/bin/sh

# Copyright © 2022 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

< /usr/share/distro-info/debian.csv \
exec awk -F, '{OFS="\t"; print($1, $3, $5, $6)}' \
| tabulate -1

# vim:ts=4 sts=4 sw=4 et
