#!/bin/sh

# Copyright © 2022 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

< /usr/share/distro-info/debian.csv \
exec awk -F, '{OFS="\t";
printf "%-8s %-12s %-12s %-12s\n", $1, $3, $5, $6}'

# vim:ts=4 sts=4 sw=4 et
