#!/bin/sh

# Copyright © 2011, 2012, 2014 Jakub Wilk <jwilk@debian.org>

# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED “AS IS” AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

if [ $# -ne 2 ]
then
    printf 'Usage: %s <deb1> <deb2>\n' "$0"
    exit 1
fi

set -e

deb1="$1"
deb2="$2"
base1=$(basename "$deb1" .deb)
base2=$(basename "$deb2" .deb)
tmpdir=$(mktemp -t -d deepdebdiff.XXXXXX)
mkdir -p "$tmpdir/a/$base1/"
dpkg-deb --raw-extract "$deb1" "$tmpdir/a/$base1/"
mkdir -p "$tmpdir/b/$base2/"
dpkg-deb --raw-extract "$deb2" "$tmpdir/b/$base2/"
cd "$tmpdir"
rc=0
diff -urN "a/$base1/" "b/$base2/" || rc=$?
cd /
rm -rf "$tmpdir"
exit $rc

# vim:ts=4 sts=4 sw=4 et
