#!/bin/sh

# Copyright © 2011-2014 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

if [ $# -ne 2 ]
then
    printf 'Usage: %s DEB1 DEB2\n' "$0"
    exit 1
fi

set -e

deb1="$1"
deb2="$2"
base1=${deb1##*/}
base2=${deb2##*/}
tmpdir=$(mktemp -t -d deepdebdiff.XXXXXX)
mkdir -p "$tmpdir/a/$base1/"
dpkg-deb --raw-extract "$deb1" "$tmpdir/a/$base1/"
mkdir -p "$tmpdir/b/$base2/"
dpkg-deb --raw-extract "$deb2" "$tmpdir/b/$base2/"
cd "$tmpdir"
rc=0
diff -urN "a/$base1/" "b/$base2/" || rc=$?
cd /
rm -rf "$tmpdir"
exit $rc

# vim:ts=4 sts=4 sw=4 et
