#!/usr/bin/python
# encoding=UTF-8

# Copyright © 2009 Jakub Wilk <jwilk@debian.org>

# Redistribution and use in source and compiled forms, with or without
# modification, are permitted under any circumstances. No warranty.

from __future__ import with_statement

import os
import sys
from collections import defaultdict
from pprint import pprint

all_archs = set()
symbols = defaultdict(set)

for filename in sys.argv[1:]:
	package, _, arch = os.path.basename(filename).partition('_')
	all_archs.add(arch)
	with open(filename) as file:
		for line in file:
			symbol = line.rstrip()
			symbols[symbol].add(arch)

for symbol, archs in symbols.iteritems():
	if archs != all_archs:
		if len(archs) <= len(all_archs) // 2:
			print '(arch=%s)' % (' '.join(sorted(archs))),
		else:
			print '(arch=%s)' % (' '.join('!%s' % arch for arch in sorted(all_archs - archs))),
	print symbol

# vim:ts=4 sw=4 noet
