#!/usr/bin/python
# encoding=UTF-8

# Copyright © 2009, 2013, 2014 Jakub Wilk <jwilk@debian.org>

# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED “AS IS” AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

import os
import sys
from collections import defaultdict

all_archs = set()
symbols = defaultdict(set)

for filename in sys.argv[1:]:
    package, _, arch = os.path.basename(filename).partition('_')
    all_archs.add(arch)
    with open(filename) as file:
        for line in file:
            symbol = line.rstrip()
            symbols[symbol].add(arch)

for symbol, archs in symbols.iteritems():
    if archs != all_archs:
        if len(archs) <= len(all_archs) // 2:
            print '(arch=%s)' % (' '.join(sorted(archs))),
        else:
            print '(arch=%s)' % (' '.join('!%s' % arch for arch in sorted(all_archs - archs))),
    print symbol

# vim:ts=4 sw=4 et
