#!/usr/bin/perl

# Copyright © 2014 Jakub Wilk <jwilk@debian.org>

# Redistribution and use in source and compiled forms, with or without
# modification, are permitted under any circumstances. No warranty.

use strict;
use warnings;

use v5.10;

use Regexp::Assemble;

my $n = 0;
my @list = @ARGV;
if (not @list) {
    local $/;
    my $list = <STDIN>;
    @list = split(' ', $list);
}
my $ra = Regexp::Assemble->new;
for my $pkg (@list) {
    $ra->add(quotemeta($pkg));
}
my $re = $ra->as_string;
$re =~ s/[(][?]:/(/g;
say $re;

# vim:ts=4 sw=4 et
