#!/usr/bin/perl

# Copyright © 2014 Jakub Wilk <jwilk@debian.org>

# Redistribution and use in source and compiled forms, with or without
# modification, are permitted under any circumstances. No warranty.

use strict;
use warnings;

use v5.10;

sub escape
{
    my ($s) = @_;
    $s =~ s/([.+])/[$1]/g;
    return $s;
}

my $n = 0;
my @list = @ARGV;
if (not @list) {
    local $/;
    my $list = <STDIN>;
    @list = split(' ', $list);
}
print(
    join(
        '|',
        map { escape($_) } @list
    ),
    "\n"
);

# vim:ts=4 sw=4 et
