#!/usr/bin/python
# encoding=UTF-8

# Copyright © 2011, 2014 Jakub Wilk <jwilk@debian.org>

# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED “AS IS” AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

import collections
import re
import sys

pymodule_match = re.compile('''
    (?:
        (?P<pymodules>
            usr/lib/pyshared/python2[.][0-9]+ | # python-support >= 0.90
            usr/share/pyshared | # python-support >= 0.90
            usr/lib/python-support/[^/]+/python2[.][0-9]+ | # python-support < 0.90
            usr/share/python-support/[^/]+ # python-support < 0.90
        ) |
        (?P<site_pkgs>
            usr/lib/python2[.][0-9]+/(?:site|dist)-packages
        )
    )
    /
    (?P<module> \w+ )
    /

''', re.VERBOSE).match

def main():
    pycentral_packages = set()
    pymodules = collections.defaultdict(lambda: (set(), set()))
    for line in sys.stdin:
        if line.startswith('FILE'):
            break
    for line in sys.stdin:
        filename, packages = line.rstrip().rsplit(None, 1)
        packages = [pkg.split('/')[-1] for pkg in packages.split(',')]
        if filename.startswith('usr/share/pyshared-data/'):
            pycentral_packages.update(packages)
        else:
            match = pymodule_match(filename)
            if match is None:
                continue
            module = match.group('module')
            (pymodules_packages, site_pkgs_packages) = pymodules[module]
            if match.group('pymodules'):
                pymodules_packages.update(packages)
            elif match.group('site_pkgs'):
                site_pkgs_packages.update(packages)
    for module, (pymodules_packages, site_pkgs_packages) in pymodules.iteritems():
        site_pkgs_packages |= pymodules_packages & pycentral_packages
        pymodules_packages -= pycentral_packages
        pymodules_packages -= site_pkgs_packages
        if pymodules_packages and site_pkgs_packages:
            print '%s:' % module
            print '  pymodules: [%s]' % ', '.join(pymodules_packages)
            print '  site-pkgs: [%s]' % ', '.join(site_pkgs_packages)
            print

if __name__ == '__main__':
    main()

# vim:ts=4 sw=4 et
