#!/bin/sh

# Copyright © 2013-2014 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

if [ $# = 0 ]
then
    printf 'Usage: %s CHANGES...\n' "${0#**/}" >&2
    exit 1
fi

exec dcmd rsync --chmod=0644 -P "$@" ssh.upload.debian.org:/srv/upload.debian.org/UploadQueue/

# vim:ts=4 sts=4 sw=4 et
