#!/bin/sh

# Copyright © 2013 Jakub Wilk <jwilk@debian.org>

# Redistribution and use in source and compiled forms, with or without
# modification, are permitted under any circumstances. No warranty.

if [ $# = 0 ]
then
    printf 'Usage: %s <changes>...\n' "$0" >&2
    exit 1
fi

dcmd rsync --chmod=0644 -P "$@" ssh.upload.debian.org:/srv/upload.debian.org/UploadQueue/

# vim:ts=4 sw=4 et
