#!/usr/bin/python3
# encoding=UTF-8

# Copyright © 2014-2025 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import re
import sys

...  # Python 3 is required

notice_re = re.compile(
    "^I: NOTICE: Log filtering will replace '(.+)' with '((?:«|<<)[A-Z]+(?:»|>>))'$".encode('UTF-8')
)

def main():
    substs = {}
    for line in sys.stdin.buffer:
        match = notice_re.match(line)
        if match is None:
            for key, value in substs.items():
                line = line.replace(key, value)
            sys.stdout.buffer.write(line)
        else:
            value, key = match.groups()
            substs[key] = value

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
