#!/usr/bin/python3

# Copyright © 2014 Jakub Wilk <jwilk@debian.org>

# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED “AS IS” AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

import re
import sys

notice_re = re.compile(
    "^I: NOTICE: Log filtering will replace '(.+)' with '(«[A-Z]+»)'$".encode('UTF-8')
)

def main():
    substs = {}
    for line in sys.stdin.buffer:
        match = notice_re.match(line)
        if match is None:
            for key, value in substs.items():
                line = line.replace(key, value)
            sys.stdout.buffer.write(line)
        else:
            value, key = match.groups()
            substs[key] = value

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
