#!/usr/bin/python3
# encoding=UTF-8

# Copyright © 2010-2022 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import argparse
import contextlib
import functools
import html
import io
import re
import sys
import urllib.request
import xml.etree.ElementTree as etree

from debian import deb822

0_0  # Python >= 3.6 is required

block_size = 0x10000

_accepted = re.compile('Accepted ([0-9][0-9a-z.:~+-]*) in').match
_pgpsig = re.compile('>(-----BEGIN PGP SIGNED MESSAGE-----\n.*\n-----END PGP SIGNATURE-----\n)', re.DOTALL).search

eprint = functools.partial(print, file=sys.stderr)

def wget(url, dest=None):
    eprint('+', url, end='')
    if dest:
        eprint('->', dest, end='')
    eprint()
    return urllib.request.urlopen(url)

def download_file(changes_item):
    sha1 = changes_item['sha1']
    url = f'https://snapshot.debian.org/file/{sha1}'
    path = changes_item['name']
    if '/' in path:
        raise RuntimeError(f'invalid file name {path!r}')
    with contextlib.closing(wget(url, dest=path)) as in_file:
        with open(path, 'wb') as out_file:
            while True:
                block = in_file.read(block_size)
                if not block:
                    break
                out_file.write(block)

def download_changes(source, version=None):
    prefix_length = 1 if not source.startswith('lib') else 4
    prefix = source[:prefix_length]
    news_url = f'https://packages.qa.debian.org/{prefix}/{source}/news.rss20.xml'
    news = wget(news_url)
    news = etree.parse(news)
    for item in news.iter('item'):
        title = item.find('title').text
        link = item.find('description').text
        m = _accepted(title)
        if m is None:
            continue
        version = version or m.group(1)
        if version == m.group(1):
            break
    else:
        raise RuntimeError('no such version')
    changes_url = etree.fromstring(link.encode('ASCII', 'replace')).get('href')
    changes = wget(changes_url).read().decode('UTF-8')
    changes = _pgpsig(changes).group(1)
    changes = html.unescape(changes)
    with open(f'{source}_{version}_snapshot.changes', 'wt', encoding='UTF-8') as out_file:
        out_file.write(changes)
    changes = io.StringIO(changes)
    changes = deb822.Changes.gpg_stripped_paragraph(changes)
    [changes] = deb822.Changes.iter_paragraphs(changes)
    for item in changes['Checksums-Sha1']:
        download_file(item)

def main():
    oparser = argparse.ArgumentParser()
    oparser.add_argument('source', metavar='SOURCE')
    oparser.add_argument('version', metavar='VERSION', nargs='?')
    options = oparser.parse_args()
    download_changes(options.source, options.version)

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
