#!/bin/sh
# Copyright © 2012 Jakub Wilk <jwilk@debian.org>

# Redistribution and use in source and compiled forms, with or without
# modification, are permitted under any circumstances. No warranty.

# This is a crude work-around for #661037.
#
# How to install:
#
# 1) Divert sbuild locally:
#
#    dpkg-divert --local --rename --add /usr/bin/sbuild
#
# 2) Install this scripts as /usr/bin/sbuild:
#
#    install /path/to/this/script /usr/bin/sbuild
#
# 3) Allow users you trust run /usr/bin/sbuild via sudo.
#
# 4) Enjoy.

set -e -u
if [ $(id -u) -ne 0 ]
then
  exec sudo -u root /usr/bin/sbuild "$@"	
fi	
exec lxc-unshare -s PID -- sudo -u "$SUDO_USER" -- /usr/bin/sbuild.distrib "$@"
