#!/bin/sh

# Copyright © 2011-2014 Jakub Wilk <jwilk@debian.org>

# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED “AS IS” AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

cd /
chroots=$(schroot --all-source-chroots -i | sed -n -e '/  Name */s//source:/p')
set -x
for chroot in $chroots
do
    sudo schroot -c $chroot -- sh -c "
        grep -Fw archive.debian.org /etc/apt/sources.list > /dev/null && exit
        apt-get update &&
        apt-get dist-upgrade --auto-remove -y &&
        apt-get clean
    "
done

# vim:ts=4 sts=4 sw=4 et
