#!/bin/sh

# Copyright © 2011-2023 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

cd /
chroots=$(schroot --all-source-chroots --exclude-aliases -l)
set -x
for chroot in $chroots
do
    sudo schroot -c $chroot -- sh -c "
        grep -Fw archive.debian.org /etc/apt/sources.list > /dev/null && exit
        apt-get update &&
        apt-get dist-upgrade --auto-remove -y &&
        apt-get clean &&
        rm -f /etc/passwd /etc/shadow &&
        rm -f /etc/group /etc/gshadow
    "
done

# vim:ts=4 sts=4 sw=4 et
