#!/bin/sh

# Copyright © 2011 Jakub Wilk <jwilk@debian.org>

# Redistribution and use in source and compiled forms, with or without
# modification, are permitted under any circumstances. No warranty.

cd /
chroots=$(schroot --all-source-chroots -i | sed -n -e '/  Name */s//source:/p')
set -x
for chroot in $chroots
do
    sudo schroot -c $chroot -- sh -c "
        grep -Fw archive.debian.org /etc/apt/sources.list > /dev/null && exit
        apt-get update &&
        apt-get dist-upgrade -y &&
        apt-get autoremove -y &&
        apt-get clean
    "
done

# vim:ts=4 sw=4 et
