#!/bin/sh

# Copyright © 2010, 2014 Jakub Wilk <jwilk@debian.org>

# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED “AS IS” AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

set -e

tmpdir=`mktemp -d`

cat > "$tmpdir/types" <<EOF
char
signed char
unsigned char
short
unsigned short
int
unsigned int
long
unsigned long
long long
unsigned long long
uint8_t
uint16_t
uint32_t
uint64_t
int8_t
int16_t
int32_t
int64_t
size_t
ssize_t
ptrdiff_t
intptr_t
uintptr_t
off_t
off64_t
float
double
long double
void *
va_list
EOF

(
  cat <<EOF
#include <stdarg.h>
#include <stddef.h>
#include <stdint.h>
#include <sys/types.h>
EOF
  nl -n rz "$tmpdir/types" | sed -r -e 's/ *([0-9]+)\t(.*)/void f__\1__(\2) { return; }/'
) | g++ -W -Wall -c -x c++ - -o "$tmpdir/tmp.o"
nm "$tmpdir/tmp.o" \
| grep ' T ' \
| sort \
| sed -r -e 's/.*f__([0-9]+)__//' \
| paste "$tmpdir/types" -
rm -rf "$tmpdir"
